### ISSUE TITLE
fail to recompile node-gyp on raspian

### ISSUE THREAD

**Issue by brainlessboy** [vesteraas/node-pitft#13]
hi,
i just tried to install node-pitft on a raspberry 3 on the latest raspbian image and got the following output, clearly the output is much longer i just added the top and the end which i think is relevant

at the beginning of the log there is this:

  CXX(target) Release/obj.target/pitft/src/framebuffer.o
../src/framebuffer.cc: In static member function 'static v8::Local<v8::Object> FrameBuffer::NewInstance(v8::Local<v8::Value>, v8::Local<v8::Value>)':
../src/framebuffer.cc:58:56: error: no matching function for call to 'v8::Function::NewInstance(const unsigned int&, v8::Local<v8::Value> [2])'
   Local<Object> instance = cons->NewInstance(argc, argv);

then a load of output from the compiler, then the npm exit resume.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.14.34-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/spghty/node_modules/pitft
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

thanks for making this, i hope you can help

cheers

**Comment by vesteraas** [comment]
Thank you for reporting this.  I will look into it.  In the meantime, a node version < 10 would probably be the best bet.

**Comment by brainlessboy** [comment]
many thanks for the quick answer, downgraded to 6.14.0 and it worked. not sure how ever how far back i do have to go :-) would 9 be ok as well?

**Comment by vesteraas** [comment]
Yes, I guess version 9 would be ok.

**Comment by brainlessboy** [comment]
9 works but requires to 'sudo node-gyp rebuild' from within the pitft package directly ...

**Comment by vesteraas** [comment]
Even better, I've fixed the problem.  I've done a few changes in the framebuffer.cc file, to remove calls to functions that was marked as deprecated.  These functions was removed in Node 10, and caused the problem you reported.  I will push a new version tomorrow.

**Edit:**

You could do a search/replace in [framebuffer.cc](url) on the following:

Replace all occurrences of `v8::String::Utf8Value` with `Nan:Utf8String`

Then, replace the line:

`Local<Object> instance = cons->NewInstance(argc, argv);`

With this:

`Local<Object> instance = Nan::NewInstance(cons, argc, argv).ToLocalChecked();`

**Comment by brainlessboy** [comment]
yeah! super cool thanks!

**Comment by vesteraas** [comment]
Well, you dont have to wait until tomorrow, I've updated my library.  :-)
