### ISSUE TITLE
Memory leak in double buffering mode: surface is not destroyed in blit()

### ISSUE THREAD

**Issue by finim** [vesteraas/node-pitft#2]
When using double buffering mode, the pitft library is leaking large amounts of memory.
I've tried to investigate the issue and found that the cairo_t *cr surface created in the FrameBuffer:Blit function(framebuffer.cc, line 113) is not destroyed afterwards. 
I've inserted a line which I think solves the issue:

``` javascript
NAN_METHOD(FrameBuffer::Blit) {
    NanScope();

    FrameBuffer *obj = ObjectWrap::Unwrap<FrameBuffer>(args.Holder());

    if (obj->drawToBuffer) {
        cairo_t *cr = cairo_create (obj->screenSurface);
        cairo_set_source_surface (cr, obj->bufferSurface, 0, 0);
        cairo_paint (cr);

       // I think this line has to be added to destroy the surface:      
        cairo_destroy(cr);
    }

    NanReturnUndefined();
}
```

**Comment by vesteraas** [comment]
I guess you're right.  I'm not able to check this easily, though.  If you could verify that this code really solves your memory issues, I will fix this.

**Comment by finim** [comment]
Thank you for the fast reply.
It's easy to check:
I've slightly modified the berries.js example in such a way that it uses a while(true) loop instead of the for-loop and switched to double buffering mode in the example (including using blit() within the loop):

``` javascript
var pitft = require("../pitft");

var fb = pitft("/dev/fb1", true); // Use double buffering mode

// Clear the screen buffer
fb.clear();

var xMax = fb.size().width;
var yMax = fb.size().height;

fb.image(x, y, "raspberry-pi.png"); // Draw the image from the file "raspberry-pi.png" at position x, y

// endless loop
while(true) {   
    var x = Math.random() * (xMax + 32) - 16;
    var y = Math.random() * (yMax + 32) - 16;
    fb.image(x, y, "raspberry-pi-icon.png");
   // blitting
    fb.blit();
}
```

You can then watch the memory usage of the process with 

watch -n 0.5 "ps aux --sort -rss | grep berries"

1) without the line inserted, the memory usage is growing constantly.
2) with the line inserted, the leak is not apparent anymore.

**Comment by vesteraas** [comment]
I've published a new version of my package.  Thank you very much!
